"""Ajustar modelo de registros

Revision ID: 2735072c5dee
Revises: 5f849133da13
Create Date: 2026-09-11 23:06:50.565991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2735072c5dee'
down_revision = '5f849133da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_requerimiento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tipos_requerimiento', ['tipo_requerimiento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_requerimiento_id')

    # ### end Alembic commands ###
