"""Crear estryctura inicial de bitacora

Revision ID: 5f849133da13
Revises: 
Create Date: 2026-09-09 23:57:22.065851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f849133da13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('naves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipos_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_requerimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nave_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nave_id'], ['naves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nave_id', 'nombre', name='uq_area_nave_nombre')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_personal_id', sa.Integer(), nullable=False),
    sa.Column('numero_registro', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_personal_id'], ['tipos_personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_bitacora',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('soporte', sa.String(length=100), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.Text(), nullable=False),
    sa.Column('nave_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('bitacora_lectora', sa.String(length=50), nullable=False),
    sa.Column('codigo_requerimiento', sa.String(length=20), nullable=False),
    sa.Column('argonite_anexo1', sa.Boolean(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('numero_registro', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('amonestacion', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditores.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['nave_id'], ['naves.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.create_index('ix_registro_codigo', ['codigo_requerimiento'], unique=False)
        batch_op.create_index('ix_registro_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_registro_personal', ['personal_id'], unique=False)
        batch_op.create_index('ix_registros_area_fecha', ['area_id', 'fecha'], unique=False)
        batch_op.create_index('ix_registros_empresa_fecha', ['empresa_id', 'fecha'], unique=False)
        batch_op.create_index('ix_registros_nave_fecha', ['nave_id', 'fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.drop_index('ix_registros_nave_fecha')
        batch_op.drop_index('ix_registros_empresa_fecha')
        batch_op.drop_index('ix_registros_area_fecha')
        batch_op.drop_index('ix_registro_personal')
        batch_op.drop_index('ix_registro_fecha')
        batch_op.drop_index('ix_registro_codigo')

    op.drop_table('registros_bitacora')
    op.drop_table('personal')
    op.drop_table('areas')
    op.drop_table('usuarios')
    op.drop_table('tipos_requerimiento')
    op.drop_table('tipos_personal')
    op.drop_table('naves')
    op.drop_table('empresa')
    op.drop_table('auditores')
    # ### end Alembic commands ###
