"""agrega tipo y nombre de persona

Revision ID: c1d47ab382ec
Revises: 9e24eefec47f
Create Date: 2026-09-22 23:55:23.019085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d47ab382ec'
down_revision = '9e24eefec47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Agregar relación de auditor con Nave y Área
    with op.batch_alter_table('auditores', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('nave_id', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('area_id', sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            None,
            'areas',
            ['area_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            None,
            'naves',
            ['nave_id'],
            ['id']
        )

    # Agregar los nuevos campos de persona
    # Primero como nullable para poder conservar los registros existentes
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tipo_personal',
                sa.String(length=20),
                nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                'nombre',
                sa.String(length=150),
                nullable=True
            )
        )

    # Migrar los datos existentes de la columna personal
    op.execute("""
        UPDATE registros_bitacora
        SET nombre = personal
        WHERE personal IS NOT NULL
    """)

    # Los registros anteriores se consideran Usuario
    op.execute("""
        UPDATE registros_bitacora
        SET tipo_personal = 'Usuario'
        WHERE tipo_personal IS NULL
    """)

    # Si existiera algún registro sin personal,
    # asignamos un valor temporal para cumplir NOT NULL
    op.execute("""
        UPDATE registros_bitacora
        SET nombre = 'Sin especificar'
        WHERE nombre IS NULL
    """)

    # Convertir los nuevos campos en obligatorios
    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.alter_column(
            'tipo_personal',
            existing_type=sa.String(length=20),
            nullable=False
        )
        batch_op.alter_column(
            'nombre',
            existing_type=sa.String(length=150),
            nullable=False
        )

        # Reemplazar índice de personal por índice de nombre
        batch_op.drop_index(
            batch_op.f('ix_registro_personal')
        )
        batch_op.create_index(
            'ix_registro_nombre',
            ['nombre'],
            unique=False
        )

        # Ya no necesitamos la columna anterior
        batch_op.drop_column('personal')

    # Aumentar longitud del nombre de tipo de personal
    with op.batch_alter_table('tipos_personal', schema=None) as batch_op:
        batch_op.alter_column(
            'nombre',
            existing_type=sa.VARCHAR(length=30),
            type_=sa.String(length=50),
            existing_nullable=False
        )

    # Aumentar longitud del nombre de tipo de requerimiento
    with op.batch_alter_table('tipos_requerimiento', schema=None) as batch_op:
        batch_op.alter_column(
            'nombre',
            existing_type=sa.VARCHAR(length=30),
            type_=sa.String(length=100),
            existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_requerimiento', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('tipos_personal', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('registros_bitacora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_registro_nombre')
        batch_op.create_index(batch_op.f('ix_registro_personal'), ['personal'], unique=False)
        batch_op.drop_column('nombre')
        batch_op.drop_column('tipo_personal')

    with op.batch_alter_table('auditores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')
        batch_op.drop_column('nave_id')

    # ### end Alembic commands ###
